name = "brew-day-scraper"
compatibility_date = "2024-12-01"
main = "src/index.ts"

[triggers]
crons = ["0 6 * * 1"]

# ── Staging ──────────────────────────────────────────────────────────
[env.staging]
name = "brew-day-scraper-staging"

[env.staging.triggers]
crons = ["0 6 * * 1"]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "beer-db-dev"
database_id = "0dd11726-22be-4bf0-98c5-a0451a3de268"
migrations_dir = "../migrations"

# ── Production ───────────────────────────────────────────────────────
[env.production]
name = "brew-day-scraper"

[env.production.triggers]
crons = ["0 6 * * 1"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "beer-db-prod"
database_id = "8466a0ec-7b87-4a39-a7a8-38d01202f85e"
migrations_dir = "../migrations"
